LIVE_URL = "http://wuvt-site:8080/playlists/live"
REQUEST_TIMEOUT = 5

ICECAST_ADMIN = ""
ICECAST_MOUNTS = []

TUNEIN_PARTNERID = ""
TUNEIN_PARTNERKEY = ""
TUNEIN_STATIONID = ""

LASTFM_APIKEY = ""
LASTFM_SECRET = ""
LASTFM_USERNAME = ""
LASTFM_PASSWORD = ""

HEALTHCHECK_WEBHOOK = ""
